name: Docker Image CI

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iss-tracker:latest
    - name: Push the Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u unggulhasan --password-stdin
        docker tag iss-tracker:latest unggulhasan/iss-tracker:latest
        docker push unggulhasan/iss-tracker:latest
